on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  Test_Result:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo "${GITHUB_HEAD_REF}"
      
  

      - name: Remove Older Build pack
        run: |
          curl -X PUT \
          -H '"Accept": "application/vnd.heroku+json; version=3"' \
          -H  '"Authorization": "Bearer 973aa154-f3e4-445f-9095-c4e098be71a9"' \
          -H  '"Content-Type": "application/json"'\
          --data "{"updates":[]}" \
          https://api.heroku.com//apps/650b637e-ffd2-45c5-bd24-11e7e49487d2/buildpack-installations 

      - name: Set newer Heroku Buildpack 
        run: echo 'The branch name is' $BRANCH_NAME

      - name: Trigger a herokubuild on sfdocs-help
        run: echo 'The branch name is' $BRANCH_NAME