on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  Test_Result:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo "${GITHUB_HEAD_REF}"
      
  

      - name: Remove Older Build pack
        run: echo 'The branch name is' $BRANCH_NAME

      - name: Set newer Heroku Buildpack 
        run: echo 'The branch name is' $BRANCH_NAME

      - name: Trigger a herokubuild on sfdocs-help
        run: echo 'The branch name is' $BRANCH_NAME