on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  Test_Result:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo "${GITHUB_HEAD_REF}"
      
  

      - name: Remove Older Build pack
        env:
         HEROKU_TOKEN: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_TOKEN"
          auth="Bearer " + "$HEROKU_TOKEN"
          echp "$auth"
          
      - name: Set newer Heroku Buildpack 
        run: echo 'The branch name is' 

      - name: Trigger a herokubuild on sfdocs-help
        run: echo 'The branch name is' $BRANCH_NAME